version: '3.8'

services:
  dockin-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - dockin-app
    networks:
      - dockin-network
    deploy:
      resources:
        limits:
          memory: 100M

  dockin-app:
    #build: .
    env_file:
      - .env
    image: khyojae/dockin-app:latest
    container_name: dockin-app-1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=DOCKin-DB
      - DB_NAME=dockindb
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - SPRING_PROFILES_ACTIVE=secret
      - TZ=Asia/Seoul
      - RACK_ENV=development
      - JAVA_OPTS=-Xmx400M -Xms256M
      - AI_SERVER_URL=${AI_SERVER_URL}
      - cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
      - cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
      - cloud.aws.region.static=${AWS_REGION}
      - cloud.aws.s3.bucket=${S3_BUCKET_NAME}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      DOCKin-DB:
        condition: service_healthy
    networks:
      - dockin-network
    deploy:
      resources:
        limits:
          memory: 512M # Spring Boot 최대치 제한

  DOCKin-DB:
    image: mysql:8.0
    container_name: dockin-db
    command:
      - --default-time-zone=+09:00
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=dockindb
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - dockin_db_data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}" ]
      timeout: 10s
      retries: 10
      interval: 5s
    networks:
      - dockin-network
    deploy:
      resources:
        limits:
          memory: 300M # MySQL 메모리 점유 제한

networks:
  dockin-network:
    driver: bridge

volumes:
  dockin_db_data: