version: '3.8'

services:
  dockin-nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - dockin-app
    networks:
      - dockin-network

  dockin-app:
    build: .
    image: khyojae/dockin-app:latest
    container_name: dockin-app-1
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=DOCKin-DB
    develop:
      watch:
        - action: rebuild
          path: ./src
        - action: sync
          path: ./src/main/resources
          target: /app/resources
    depends_on:
      DOCKin-DB:
        condition: service_healthy
    networks:
      - dockin-network

  DOCKin-DB:
    image: mysql:8.0.44
    container_name: dockin-db
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "Dockin"
    ports:
      - "3306:3306"
    volumes:
      - dockin_db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234" ]
      timeout: 5s
      retries: 10
      interval: 5s
    networks:
      - dockin-network

networks:
  dockin-network:
    driver: bridge

volumes:
  dockin_db_data: